### ISSUE TITLE
A non used output in the solution of the xml tool wrapper

### ISSUE THREAD

**Issue by Chabrier** [eancelet/training-material#4]
A non used output in the solution of the xml tool wrapper is specified, but the command does not seem to output something.

This could be confusing.

**Comment by neoformit** [comment]
Resolved by [PR #7](https://github.com/eancelet/training-material/pull/7), but I'm pretty sure it's not necessary to have an output for the tool to appear in the Galaxy history? Should the output be deleted instead?
